### ISSUE TITLE
Updating a secret - Is the apply command enough ?

### ISSUE THREAD

**Issue by kriegalex** [ehlesp/smallab-k8s-pve-guide#10]
Hi,
After launching Nextcloud, I've seen it complaining about the redis connection in the logs.

`RedisException: WRONGPASS invalid username-password pair or user is disabled.`

I've reread G033 and noticed a warning about the `redis.pwd` format. I updated the file by checking there are no line breaks and I switched to a way longer password without special characters (just in case).

After applying the change (`kubectl apply -k`), I noticed that if I go to my agent VM and browse to the config, the `config.php` hasn't changed.

`$ sudo cat /mnt/nextcloud-ssd/html/k3smnt/config/config.php`

```
'redis' =>
  array (
    'host' => '10.43.100.1',
    'password' => 'OLD_PASSWORD',
    'port' => 6379,
  ),
```

What is the correct way to have such files updated ?

**Comment by kriegalex** [comment]
Since this was a test Nextcloud deployment, I simply removed everything and cleaned all the `k3smnt` folders.

`$ kubectl kustomize $HOME/k8sprjs/nextcloud | kubectl delete -f -`
```
$ sudo rm -r /mnt/nextcloud-ssd/html/k3smnt
$ sudo rm -r /mnt/nextcloud-ssd/db/k3smnt
$ sudo rm -r /mnt/nextcloud-hdd/data/k3smnt
$ sudo mkdir ...
```
`$ kubectl apply -k ...`

I'm still curious on how to do that properly on a live service.

And it didn't fix the `WRONGPASS` issue. I really don't see where the issue is, the redis chapter is pretty straightforward.

**Comment by kriegalex** [comment]
Seems like Nextcloud's config.php with Redis 6+ should now [have a user defined](https://github.com/nextcloud/nextcloudpi/issues/1652#issuecomment-1445141639).

```
'redis' =>                           
array (                                                                 
    'host' => '/var/run/redis/redis.sock',
    **'user' => 'default',**     
    'port' => 0,
    'timeout' => 0.0,
    'password' => 'PASSWORD',
)
```

I'm trying to see if I can add this via the redis.conf.

**Comment by kriegalex** [comment]
For now, I'm fixing it manually, by scaling down the nextcloud server and editing the config.php file via the VM command line (k3sagentX).

```
$  kubectl scale statefulset nxcd-server-apache-nextcloud -n nextcloud --replicas=0
$  sudo nano ......../config.php
$  kubectl scale statefulset nxcd-server-apache-nextcloud -n nextcloud --replicas=1
```

**Comment by ehlesp** [comment]
First know that my current setup is different (simpler) from the one explained in my guides. Still, I do have a Nextcloud instance running with Redis but I don't remember facing that particular problem, even after a number of update cycles. Next, I detail you my current setup:

- Nextcloud: 26.0.2-apache
- Redis: 7.0.11-apache
- MariaDB: 11.0.2-jammy
- K3s: 1.26.5+k3s1

I've revised my configuration and I haven't applied any fix related to that Redis user issue you've met. I just specify the password (a long alphanumerical one) and it has been working fine all this time for me. Your manual solution seems to be similar to what's indicated in the last message of the nextcloud issue you've linked. 

Regarding what you find in the `k3smnt` folder directly in the agent VM, it's not surprising that you don't see the `config.php` file changed because that's a file replaced in the container instance kept **in memory**. To see what's the effective configuration applied in the running instance, you can shell **into the container itself**, as I explain in the ["Shell access into your containers" found in the G036 guide](https://github.com/ehlesp/smallab-k8s-pve-guide/blob/main/G036%20-%20Host%20and%20K3s%20cluster%20%7E%20Monitoring%20and%20diagnosis.md#shell-access-into-your-containers).

I'll close this issue since there's no problem with the guides themselves in this case.

**Comment by kriegalex** [comment]
Hi @ehlesp ,
I did finally find the issue:

My first lead was this comment on Reddit 

![image](https://github.com/ehlesp/smallab-k8s-pve-guide/assets/2486182/da7515e7-6b60-409b-9351-01cc5fac5be9)

After checking content of `redis.config.php`, it seems indeed that having the `REDIS_HOST` variable set creates additional processing on the `$CONFIG`.

``` 
<?php
if (getenv('REDIS_HOST')) {
  $CONFIG = array(
    'memcache.distributed' => '\OC\Memcache\Redis',
    'memcache.locking' => '\OC\Memcache\Redis',
    'redis' => array(
      'host' => getenv('REDIS_HOST'),
      'password' => (string) getenv('REDIS_HOST_PASSWORD'),
    ),
  );

  if (getenv('REDIS_HOST_PORT') !== false) {
    $CONFIG['redis']['port'] = (int) getenv('REDIS_HOST_PORT');
  } elseif (getenv('REDIS_HOST')[0] != '/') {
    $CONFIG['redis']['port'] = 6379;
  }
}
```

Checking the file `server-apache-nextcloud.statefulset.yaml`, the var `REDIS_HOST` is set there. Commenting it made the NC instance work again without errors. By the way, with this issue, any call to `php occ` resulted in a `WRONGPASS` failure, it is not simply an annoying thing in the logs.

But the issue doesn't stop there. If you simply remove the `REDIS_HOST`, people creating for the first time the pod will have a `config.php` that does not contain the redis config array, since it is injected by `redis.config.php`.

Please let me know if I say something wrong, but the procedure is as following.

1. Apply kustomize config as described in G033 guide.
2. Comment the REDIS_HOST variable in `server-apache-nextcloud.statefulset.yaml`.
3. Re-apply the kustomize config.
4. Enjoy a bug free Nextcloud.

**Comment by ehlesp** [comment]
I've double checked my own current Nextcloud statefulset and I do have the `REDIS_HOST` in place perfectly fine, and I've had it there in every update. If you remove it, Nextcloud will work because it won't try to use Redis at all, as you can see in the piece of code you pasted. So you haven't fixed the issue, you just have **disabled** Redis for Nextcloud, which won't affect much the Nextcloud's server performance if the instance is just for personal use. I think you might have missed something in your own Nextcloud statefulset like not putting the right `name` or `key` in the `valueFrom` of the variable, or something of the sort.

Again, I don't see any issue here concerning the guides. Please stop commenting in this thread since it's a **closed matter**.
