### ISSUE TITLE
Using GitHub Pages or Wiki for content

### ISSUE THREAD

**Issue by ericvoshall** [ehlesp/smallab-k8s-pve-guide#2]
Hey! This guide is absolutely awesome and incredibly thorough. One frustration when going through is that going from one "chapter" to the next is kind of a hassle - there's no "Next Page" or easily accessible table of contents to allow users to progress or get a sense of where they are in the entire thing.

Any thoughts on moving the content to the repo wiki, GitHub Pages, or even just a "Next Section" link at the bottom of each file?

I'd be happy to help contribute if needed!

**Comment by ehlesp** [comment]
Many thanks for your appreciation, Eric. Since I wrote the whole guide series on Visual Studio Code, I hadn't realized that issue till you've pointed out! Now, about how to solve this, the best way will be to add `previous`, `TOC` and `next` links right above the **References** section of each guide (or right at the end of the guide's content). This will be the fastest way for me, and also the most adequate, since I don't want to tie the project to the GitHub platform.

Hopefully around next week I'll have time to do the modification. Stay tuned!

**Comment by ehlesp** [comment]
Check out the most recent version (`v1.2.0`). I've added a **Navigation** section at the bottom of each guide, from which you can go to the previous or following guide, or return to the TOC.
